version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_papelaria
    restart: always
    tty: true
    working_dir: /var/www
    ports:
      - 10080:80

    volumes:
      - ./:/var/www
      - ./docker-files/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network
    links:
      - db
      - db_test
    #NGINX service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: always
    tty: true

    ports:
      - "8100:80"
      - "8143:443"

    volumes:
      - ./:/var/www
      - ./docker-files/nginx/conf.d/:/etc/nginx/conf.d

    networks:
      - app-network
    links:
     - db
     - db_test
  # mysql - Service
  db:
    image: mysql:5.7.22
    container_name: db
    restart: always
    tty: true

    ports:
      - 9009:3306
    environment:
      MYSQL_DATABASE: papelaria_db
      MYSQL_ROOT_PASSWORD: root

    volumes:
      - mysqldbdata:/var/lib/mysql
      - ./docker-files/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network
  db_test:
    image: mysql:5.7.22
    container_name: db_test
    restart: always
    tty: true

    ports:
      - 9010:3306
    environment:
      MYSQL_DATABASE: papelaria_db_test
      MYSQL_ROOT_PASSWORD: root

    volumes:
      - mysqldbdata:/var/lib/mysql
      - ./docker-files/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network
volumes:
  mysqldbdata:
    driver: local
networks:
  app-network:
    driver: bridge






